@ECHO OFF

python .\src\ip.py
IF ERRORLEVEL 1 (
    :: EXIT /B: SAÍDA DO SCRIPT EM LOTE ATUAL
    EXIT /B %ERRORLEVEL%
)

START "PRINCIPAL" python .\src\main.py

:: /C: OPÇÕES (CARACTER 'T'); /N: OCULTA OPÇÕES; /M: MENSAGEM
CHOICE /C T /N /M "PRESSIONE T PARA [T]ERMINAR O PROGRAMA"
IF ERRORLEVEL 1 (
    CALL :KILLSCRIPT
    EXIT /B %ERRORLEVEL%
)

:: EXIT /B: RETORNA CONTROLE PARA INSTRUÇÃO APÓS CHAMADA
:KILLSCRIPT
    TASKKILL /FI "WINDOWTITLE EQ PRINCIPAL"
    EXIT /B %ERRORLEVEL%

