@ECHO OFF

python .\src\ip.py
IF ERRORLEVEL 1 (
    EXIT /B %ERRORLEVEL%
)

START "PRINCIPAL" python .\src\main.py

CHOICE /C T /N /M "PRESSIONE T PARA [T]ERMINAR O PROGRAMA"
IF ERRORLEVEL 1 (
    CALL :KILLSCRIPT
    EXIT /B %ERRORLEVEL%
)

:KILLSCRIPT
    TASKKILL /FI "WINDOWTITLE EQ PRINCIPAL"
    EXIT /B %ERRORLEVEL%

